import os
import spacy
import numpy as np
import connect
import config
import re
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
import gensim.downloader as api
import tqdm
from nltk import tokenize
from operator import itemgetter
import math
import nltk
from gensim.models import KeyedVectors
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 

connect.connect()
model = KeyedVectors.load("test.d2v")
stop_words = set(stopwords.words('english'))
nlp = spacy.load("en_core_web_lg") #setting up spacy nlp


tent = "FINANCE,STATISTICS,ANALYSIS,FEE,COST,PURCHASE,ACCOUNTING,REPORT,SHEETS,EXCEL,MONEY,MANAGEMENT,BALANCE,THEORY,PRACTICAL,BUSINESS,SYSTEMS,ADVANCED,TAX,AUDITING,TAX FINANCE,RELIGION,SOCIETY,HUMANS,COMMUNITY,CULTURE,HUMANBEHAVIOR,WORLDSTUDIES,INTERNATIONALSTUDIES,CHILDREN,FAMILYSTUDIES,STUDY,BEHAVIOR,LANGUAGE,INTRODUCTORY,ELEMENTARY,LANGUAGESTUDY,ARABIC,HISTORY,ARCHAEOLOGY,ARTIFACTS,AMERICA,AMERICANSTUDIES,INTERMEDIATE,CIVILIZATIONS,GRAPHICS,TECHNOLOGY,DIGITALMEDIA,DESIGN,COMPUTINGTECHNOLOGY,MEDIA,ART,DRAWING,FUNDAMENTALS,CREATIVE,PAINTING,SCULPTING,PHOTOGRAPHY,CAMERA,CAPTURE,LENS,DIGITALDESIGN,FIGURES,COMPUTERGRAPHICS,TECHONOLOGY,ANIMATION,MOVING,,WEBSITE,WEBDESIGN,COMPUTERS,CREATIVITY,SHOT,DIGIALMEDIA,PROJECT,SENIOR,PORTFOLIO,WESTERNSTUDIES,WORLD STUDIES,EATERNSTUDIES,ASIANSTUDIES,FASHION,CUTLURE,EASTERNSTUDIES SOCIETY,MODERN,EASTERNSTUDIES,MEDIEVAL,RENAISSANCE,INTERNSHIP,CAPPING,ATHLETICTRAINING,HUMANBODY,PHYSICAL,PHYSICALEDUCATION,BODY,SPORTS,ATHLETICS,WELLBEING,BIOLOGY,PLANTS,ANIMALS,CELLS,SCIENCE,LIFE,ANATOMY,BODILYFUNCTIONS,NUTRITION,FOOD,MICROBIOLOGY,BACTERIA,FUNGI,VIRUSES,MICRO,ORGANISMS,ENVIRONMENT,PLANT,PLANTCELLS,IMMUNESYSTEM,FORENSICS,DNA,NATURAL,ENVIORNMENT,EVOLUTION,SKIN,FRESHWATER,WATER,INVERTEBRATE,ZOO,ENGINEERING,MEDICINE,PARASITES,SICKNESS,HEALTH,DISEASE,MOLECULES,CELLSTRUCTURE,BUSINESSADMINISTRATION,LITERACY,BILLS,TAXES,STOCKS,INVESTING,MORTGAGE,SAVINGS,JOB,GLOBAL,INTERNATIONAL,HUMANRESOURCES,CONDUCT,WEALTH,MARKETING,PRINCIPLES,ADVERTISING,SALES,ENTREPRENEURSHIP,PERSONAL,LAW,CORPORATE,PEOPLE,REGULATIONSS,BONDS,OPERATIONS,CASHFLOWS,SUPPLYANDDEMAND,OPERATIONCHAIN,REGULATIONS,EQUITIES,TRADING,WORK,LABOR,RELATIONSHIPS,EMPLOYMENT,WORKPLACE,INTERNATIONALTRADING,COMMUNICATIONS,CAREER,CAREERDEVELOPMENT,GROWTH,CHEMISTRY,ELEMENTS,ENERGY,ATOMS,PARTICLES,ORGANIC,CARBON,REACTIONS,RELIGIOUSSTUDIES,CATHOLICSTUDIES,SPIRTUALITY,BELIEFSYSTEMS,MATH,EQUATIONS,LAB,CHEMISTY,BIOCHEMISTRY,MECHANICALCHEMISTRY,STRUCTURE,PROCESSES,ANALYTICS,CALCULATIONS,HEAT,TEMPERATURE,COMPUTATIONS,QUANTUMMECHANICS,INORGANIC,RESEARCH,CHINESE,PUBLICSPEAKING,SPEECH,PRESENTATION,TALKING,PRESENTATIONS,SPEAKING,DIGITAL,DIGITALTOOLS,LEARNING,ONLINE,SPECIALTOPICS,DEBATE,ARGUMENTS,RELATIONS,WRITING,TOOLS,JOURNALISM,ARTICLES,JOURNALIST,NEWS,TELEVISION,COMMUNICATION,PUBLIC,RELATIONSHIP,EDITING,PUBLICPRESENTATION,SKILLS,TECHNIQUES,STRATEGY,BROADCAST,PUBLICAFFAIRS,PUBLICRELATIONS,REPORTING,CONSUMER,MAGAZINES,READING,GRAPHICDESIGN,PROBLEMSOLVING,THINKING,CRITICALTHINKING,ETHICS,RADIO,DATA,GENDERSTUDIES,VISUALS,STORY,CAMPAIGN,MANAGMENT,COPYWRITING,PRESS,COMPENTANCY,GAMING,GAMEDESIGN,SOFTWARE,SOFTWAREDEVELOPMENT,CODING,PHP,HTML,SQL,DEVELOPMENT,INFORMATIONSYSTEMS,PROJECTMANAGER,PYTHON,PROGRAMMING,JAVA,OOP,INFORMATIONTECHNOLOGY,IT,NETWORKING,DEVICES,OPERATINGSYSTEMS,IBM,ZOS,DATABASES,QUERY,ORGANIZATIONS,FILTERING,SORTING,SEARCHING,SECURITY,OPERATINSYSTEMS,CYBERSECURITY,PROJECTMANAGEMENT,LEAD,ORGANIZATION,UNIX,COMPUTERSCIENCE,CSS,LETLANG,COMPILERS,SYNTAX,ECOMMERCE,HACKING,TESTING,ROBOTICS,MOBILE,INTERNET,TYPESCRIPT,OPERTATINGSYSTEMS,DEBUGGING,WIRELESS,NETWORK,DATAMANAGEMENT,DATABASE,ALGORITHMS,PATTERNS,COMPILING,DIGITALGRAPHICS,TOPICS,CAPPNG,NFORMATIONSYSTEMS,CRIMINALS,CRIMINALJUSTICE,CLOUDCOMPUTING,CLOUD,INFRASTRUCTURE,POLICY,RULES,DRUGS,DRUGABUSE,CRIME,JAPAN,SPAIN,EUROPE,CARIBBEAN,SPANISH,GLOBALSTUDIES,GLOBALISSUES,FRANCE,EUROPEANSTUDIES,FILM,MOVIES,ACTING,ACTORS,DATASCIENCE,DATAANALYSIS,R,ITALY,WORLDHISTORY,VISUALIZATION,DATAVISUALIZATION,CHARTS,TABLES,ARTIFICIALINTELLIGENCE,MACHINELEARNING,COMPUTERENGINEERING,ECONOMICS,SEX,GENDER,CIVILIZATION,DATAMINING,DATAPREDICTION,PREDICTIVE,CAPSTONE,SUPPLY,DEMAND,PRICES,SOCIAL,ENVIRONMENTALSTUDIES,BANKING,FEDERALRESERVE,CASH,BANKS,MARKETS,HEDGEFUNDS,FIRMS,PHILOSOPHYMONEY,FOUNDATIONAL,EDUCATION,TEACHING,SCHOOL,TEACHER,GENRE,BOOKS,ENGLISH,POETRY,POEMS,DRAMA,COLLEGE,LITERATURE,NOVEL,ESSAY,THEATRE,FOREIGNLANGUAGE,WORDS,STYLE,GRAMMAR,LINGUISTICS,FICTION,THEMES,SHAKESPEARE,PLAY,SCRIPT,SHORTSTORIES,NOVELS,EXECUTIVESUMMARY,FORMS,OLDLITERATURE,SCRIPTS,LOVE,FILMSTUDIES,IRISH,BRITISH,DIRECTING,GREECE,COMPOSITION,TECHNICAL,RELIGIOUS,JUNIOR,SEMINAR,WRITNG,JUDAISM,WORKSHOP,CHARACTER,GEOLOGY,ROCKS,CRUST,EARTH,STONES,EARTHSCIENCE,ENVIRONMENTAL,FIELDWORK,INPERSON,INFIELD. EXPERIENCE,POLITICS,PUBLICHEALTH,NATURE,PUBLICPOLICY,ENVIRONMENTALSCIENCE,ECOLOGY,ECOSYSTEM,PRACTICE,FISH,CHEMICALS,TOXINS,SUBSTANCES,PLANNING,COMMERCE,PROCESS,FASHIONDESIGN,VISUAL,MERCHANDISE,EVENTPLANNING,EVENTS,SHOWS,EVENT,PRODUCT,SAFETY,BRANDS,BRANDING,LICENSING,SUSTAINABILITY,POLUTION,RETAIL,SUPPLYCHAIN,KNITWEAR,MODERNHISTORY,PERSONALGROWTH,STRATEGIES,FRENCH,WORKSHOPS,ORAL,GAMES,COMPUTER,GAME,GERMAN,FOREIGNLANGAUGE,BACKGROUND,HUMANSTUDIES,PROGRESS,MYTHOLOGY,ANCIENT,GODS,PANTHEON,PRINCIPLE,RELATIVE,STATUS,PEACE,MISSION,BORDER,HUMAN,NATIONAL,CONFLICT,ABROAD,LEADERSHIP,GOLDENAGE,ISSUES,SICK,ADULT,FEED,ACTIVE,COOK,MOVE,MONITOR,DIET,STOMACH,PATIENT,STRENGTH,MUSCLE,WEIGHT,RECOVER,SWIM,HURT,BREAK,HELP,NURSE,BABY,SAVE,CPR,TWIST,TRAIN,STRAIN,SCRATCH,RUN,HARM,PACE,ARM,SMOKE,BONE,JOINT,EXERCISE,JESUS,DISCIPLESHIP,FAITH,CHRISTIANITY,LETTER,EVIDENCE,CHART,DREAM,CONSIDERATION,DETAIL,INTERVIEW,BATTLE,FIGHT,ATTACK,WAR,WOMEN,WOMENSTUDIES,POLITICAL,BLACKHISTORY,RACE,CATHOLIC,NEWYORK,CHANGE,ROME,CHURCH,AFRICANAMERICAN,EAST,COLONIAL,LATINAMERICA,ITALIANAMERICAN,EXPERIENCE,AMERICANHISTORY,AFRICA,ASIA,TRADITIONAL,CHINA,IMMIGRATION,MANHOOD,ROCKANDROLL,US,MUSIC,REVOLUTION,DIPLOMATIC,FEMINISM,VIETNAM,DEATH,PRESIDENCY,NAPOLEAN,DRUG,TRADE,CIVILWAR,INTERNAL,RECONSTRUCTION,HONORS,MORALS,FIRSTYEAR,FDR,SENIORYEAR,MORAL,FOUNDATIONS,QUANTITATIVE,AESTHETICS,EXPRESSION,IDEAL,CONTRACT,THESIS,PERSPECTIVES,HUMANITIES,PROFESSIONALSTUDIES,BUSINESSMANAGEMENT,LEGAL,INNOVATION,ITALIAN,CINEMA,CONVERSATION,JAPANESE,LATIN,SELFDEVELOPMENT,CRITICALREADING,PRECALCULUS,LOGIC,REASONING,TRANSFER,SEMINARS,ALGEBRA,DISCRETEMATHEMATICS,LINEARALGEBRA,DIFFERENTIALEQUATIONS,PROBABILITY,OPERATIONALMODELS,APPLIEDSTATISTICS,CALCULUS,MATHEMATICS,MATHPRACTICUM,APPLIEDMATHEMATICS,ABSTRACTALGEBRA,COMPLEXANALYSIS,COMPUTATIONAL,MATHEMATICALANALYSIS,NUMERICALANALYSIS,COMBINATORICS,COUNTING,FINITESTRUCTURES,GEOMETRY,FUNDAMENTALCONCEPTS,ELEMENTARYTOPOLOGY,VIDEO,PRODUCTION,MEDIASTUDIES,TOOLBOX,INTERACTIVE,AUDIO,SOCIALMEDIA,STORYTELLING,PERFORMANCE,ELECTRONICMEDIA,METHODS,CRITICISM,ETHNICITY,IDENTITY,REPRESENTATION,CURRENTISSUES,EXPERIMENTAL,DOCUMENTARY,CURRENT,FILMMAKING,SCREENWRITING,POSTPRODUCTION,MULTICAMERA,STUDIES,CAUSE,PROGNOSIS,TREATMENT,DISEASEPREVENTION,BLOOD,MEDICAL,CLINICAL,MICROSCOPY,VOCALS,SINGING,INDEPENDENT,CHORAL,SINGINGVOCALS,BEGINNING,VOCALSKILLS,SINGERS,MEN,INSTRUMENTAL,CHAPEL,CHOIR,GOSPEL,CHAMBER,BRASS,ENSEMBLE,FLUTE,PIANO,WOODWIND,ORCHESTRA,HANDBELL,PERCUSSION,SYMPHONIC,WIND,GUITAR,SIGHTREADING,INTRODUCTION,JAZZ,SOUNDS,BAROQUE,MASTERS,WORLD,POPULAR,MUSICINDUSTRY,MOTIONPICTURE,BEETHOVEN,SCHUBERT,OPERA,CLASSICAL,JUSTICE,REALPROPERTY,TITLESEARCH,JUVENILELAW,PROCEDURES,CRIMINAL,WILLS,TRUSTS,ESTATES,BUSINESSLAW,FAMILYLAW,CORPORATELAW,CIVILLITIGATION,LABORRELATIONS,PHILOSOPHY,PHILOSOPHICAL,VIEWS,VALUES,PRAGMATISM,EXISTENTIALISM,FREEWILL,PREFERENCES,BEAUTYPRINCIPLES,ARTISTICTASTE,SYMBOLICLOGIC,CONTEMPORARY,ANALYTIC,CRITICALHISTORY,METAPHYSICS,REALITY,CONSCIOUSNESS,MARX,COMMUNISM,ECONOMIC,MIND,VOLLEYBALL,TEAM,GOLF,ARCHERY,CONDITIONING,TENNIS,DANCE,BOXING,PHYSIOLOGY,RACQUETBALL,BALLET,FENCING,SAILING,SWIMMING,SOCCER,COACHING,KARATE,YOGA,BASKETBALL,SPRINGBOARD,DIVING,BASEBALL,FLYFISHING,FOOTBALL,SCUBADIVING,MOVEMENT,PHYSICS,COSMOLOGY,PHYSICSSCIENCE,GENERAL,AMERICAN,GOVERNMENT,CRTICIALTHINKING,POLITICALSCIENCE,CULTURES,STATE,LOCAL,POLLING,SURVEY,INSTRUMENT,VOTING,DATACOLLECTION,RIGHTS,POLITICALTHOUGHT,CATHOLICS,DEVELOPINGAREAS,EUROPEAN,MODELUNITEDNATIONS,PUBLICOPINIONS,MOVEMENTS,PREJUDICE,DISCRIMINATION,ADMINISTRATION,MANGEMENT,FINANCIALMANAGEMENT,IMPLEMENTATION,GOALS,OBJECTIVES,ECONOMY,FEMINIST,LATINAMERICAN,AFRICANPOLITICS,ENVIRONMENTALPLANNING,CONGRESSTODAY,MORALITY,PSYCHOLOGY,PERSONALITY,THEORIES,SITUATIONS,SOCIALENVIRONMENTS,BEHAVIORS,ABNORMAL,UNUSUALPATTERNS,EMOTION,THOUGHT,DIFFERENCES,PSYCHOBIOLOGICAL,GROUPS,INSTITUTIONS,EXCEPTIONALCHILD,EDUCATIONAL,SLEEPPSYCHOLOGY,PSYCHOBIOLOGY,PROFESSIONALISSUES,HUMANFACTORS,ADOLESCENCE,LIFESPAN,COUNSELING,MEASUREMENT,EVALUATION,COMPARISON,COGNITIVE,MENTALPROCESSES,PERCEPTION,WORLDRELIGIONS,SUPERVISEDRESEARCH,WRITTENANALYSIS,LEGALISSUE,SPIRITUALITY,BIBLE,STORIES,INDIA,CULTURAL,GREEK,SOCIOLOGY,SOCIALETHICS,JUDAEOCHRISTIAN,SCRIPTURES,CATHOLICTHOUGHT,PRISON,PRAXIS,PRISONERS,LIBERATION,THEOLOGY,MARGINALIZEDCOMMUNITIES,ECONOMICEQUALITY,PUBLICLIFE,SOCIALDISINTEGRATION,SCIENTIFICSTUDY,SOCIALWORK,DOMESTICVIOLENCE,PREVENTION,SOCIALSERVICE,ALCOHOLISM,FAMILY,POPULATION,ADDICTIONS,DIVERSEPOPULATIONS,JUNIORFIELDEDUCATION,FIELDEXPERIENCE,SOCIALCHANGE,SOCIALPROBLEMS,SOCIALDEVIANCE,RELIGIOUSSOCIOLOGY,JUVENILEDELINQUENCY,COMMUNITYSOCIOLOGY,EDUCATIONSOCIOLOGY,POPULARCULTURE,TRENDS,SOCIALINEQUALITY,INEQUALITY,SOCIALTHEORY,RESOURCES,HISPANICCARIBBEAN,HISPANIC,HERITAGESPEAKERS,SPANISHCINEMA,CONCEPTS,STUDYTOUR,GUIDE,TODAY,INTENSIVE,WRITERS,PROFESSIONAL,TRANSLATION,SPANISHAMERICAN"
test3 = tent.split(',')


def consumeResourceId(resourceId):
    fileUri = connect.getResourcePath(resourceId)

    return(scrapetTxt(fileUri))

def scrapetTxt(filePath):
    file1 = open(filePath, 'r', encoding="utf-8")
    txt = file1.read()
    
    return(scrape(re.sub('[^A-Za-z0-9\s]+', '', txt)))

def check_sent(word, sentences): 
    final = [all([w in x for w in word]) for x in sentences] 
    sent_len = [sentences[i] for i in range(0, len(final)) if final[i]]
    return int(len(sent_len))

def get_top_n(dict_elem, n):
    result = dict(sorted(dict_elem.items(), key = itemgetter(1), reverse = True)[:n]) 
    return result

def scrape(string):
    #return nlp(string).ents
    total_words = string.split()
    total_word_length = len(total_words)
    total_sentences = tokenize.sent_tokenize(string)
    total_sent_len = len(total_sentences)

    tf_score = {}
    for each_word in total_words:
        each_word = each_word.replace('.','')
        if each_word not in stop_words:
            if each_word in tf_score:
                tf_score[each_word] += 1
            else:
                tf_score[each_word] = 1

    # Dividing by total_word_length for each dictionary element
    tf_score.update((x, y/int(total_word_length)) for x, y in tf_score.items())

    idf_score = {}
    for each_word in total_words:
        each_word = each_word.replace('.','')
        if each_word not in stop_words:
            if each_word in idf_score:
                idf_score[each_word] = check_sent(each_word, total_sentences)
            else:
                idf_score[each_word] = 1

    # Performing a log and divide
    idf_score.update((x, math.log(int(total_sent_len)/y)) for x, y in idf_score.items())

    tf_idf_score = {key: tf_score[key] * idf_score.get(key, 0) for key in tf_score.keys()}

    return get_top_n(tf_idf_score, 10)

def magicMatch(tags, keywords):
    tagList = []
    
    for tag in tags:
        for keyword in keywords:
            if not keyword.isdigit():
                try:
                    val = model.similarity(tag.lower(), keyword.lower())
                    if(val > 0.65):
                        tagList.append(tag)
                except KeyError:
                    pass

    return(list(set(tagList)))

def initialSetup():

    nltk.download('stopwords')
    nltk.download('punkt')

    #model = api.load("word2vec-google-news-300") #choose from multiple models https://github.com/RaRe-Technologies/gensim-data
    model = api.load("glove-wiki-gigaword-300") #choose from multiple models https://github.com/RaRe-Technologies/gensim-data
    model.save("test.d2v")


